name: ✨ Feature Request
description: Suggest a new feature or enhancement for dynamic-moe-router-kit
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea clearly so we can evaluate it.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      options:
        - label: I searched existing issues and didn't find a similar feature request
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Any alternative approaches or workarounds you've thought of

  - type: dropdown
    id: backend
    attributes:
      label: Target Backend(s)
      description: Which backend(s) should this feature support?
      multiple: true
      options:
        - PyTorch
        - JAX/Flax
        - TensorFlow
        - Backend-agnostic
        - Not applicable

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (simple configuration or parameter addition)
        - Medium (new algorithm or significant logic changes)
        - High (major architectural changes or new components)
        - Unsure

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, research papers, or examples about the feature request here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature