# Prometheus configuration for dynamic-moe-router-kit monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: "dynamic-moe-router-kit"
    environment: "development"

rule_files:
  - "alerts/*.yml"

scrape_configs:
  # Application metrics
  - job_name: "dynamic-moe-router"
    static_configs:
      - targets: ["localhost:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    
  # Python application metrics
  - job_name: "python-app"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"
    
  # Model performance metrics
  - job_name: "model-metrics"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/model/metrics"
    scrape_interval: 30s
    
  # System metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
      
alertmanager:
  static_configs:
    - targets:
      - "localhost:9093"